 tasks:
  - name: Make sure pip is up-to-date
    command: /home/gitpod/.pyenv/versions/3.8.10/bin/python3.8 -m pip install --upgrade pip
  - name: install basic DS packages via pip
    command: pip install pandas scipy